# Generated by Django 4.0.2 on 2022-07-22 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_and_time_of_incident_start', models.DateTimeField()),
                ('date_and_time_of_incident_end', models.DateTimeField()),
                ('cause_of_incident', models.TextField()),
                ('actions_taken', models.TextField()),
                ('equipment_used', models.TextField()),
                ('identify_substance', models.TextField()),
                ('material_run_off_property', models.BooleanField(default=False)),
                ('agencies_notified', models.BooleanField(default=False)),
                ('Environment_affected', models.BooleanField(default=False)),
                ('employee_chemical_exposure', models.BooleanField(default=False)),
                ('employee_injured', models.BooleanField(default=False)),
                ('employee_phone_number', models.CharField(max_length=15)),
                ('public_chemical_exposure', models.BooleanField(default=False)),
                ('public_injured', models.BooleanField(default=False)),
                ('debrief_attendance', models.TextField()),
                ('positive_notes', models.TextField()),
                ('areas_of_improvement', models.TextField()),
                ('debrief_date_time', models.DateTimeField()),
                ('debrief_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DebriefCommander', to=settings.AUTH_USER_MODEL)),
                ('incident_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commander', to=settings.AUTH_USER_MODEL)),
                ('incident_type', models.ForeignKey(help_text='IF OTHER PROVIDE DESCRIPTION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Report.incidenttype')),
                ('physical_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Report.physicaldescription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
