# Generated by Django 4.0.2 on 2024-03-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_screport'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='firereport',
            name='cause_of_incident',
            field=models.CharField(max_length=140),
        ),
    ]
