# Generated by Django 4.0.2 on 2024-03-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_yesno_firereport_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firereport',
            name='Test',
        ),
    ]
