# Generated by Django 4.0.2 on 2024-03-10 18:20

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_yesno_alter_firereport_cause_of_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='loss_of_consciousness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LossOfConsciousness', to='Report.yesno'),
        ),
    ]
