# Generated by Django 4.0.2 on 2024-03-10 18:22

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_alter_medicalreport_loss_of_consciousness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='loss_of_consciousness',
            field=models.BooleanField(default=False),
        ),
    ]
