# Generated by Django 4.0.2 on 2024-03-10 18:50

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_alter_medicalreport_loss_of_consciousness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesno',
            name='description',
        ),
        migrations.AddField(
            model_name='yesno',
            name='bool',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
