# Generated by Django 4.0.2 on 2024-03-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_alter_medicalreport_loss_of_consciousness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yesno',
            old_name='description',
            new_name='bool',
        ),
    ]
