# Generated by Django 4.0.2 on 2024-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_rename_description_yesno_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesno',
            name='bool',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
